name: MCTeleports
main: org.unixminecraft.mcteleports.bukkit.MCTeleports
version: 0.0.8
author: unixminecraft
api-version: 1.15

depend: [Multiverse-Core]

commands:
  sethome:
    description: Set your home
  home:
    description: Teleport to your home
  setspawn:
    description: Set the world's spawn
  spawn:
    description: Teleport to the spawn
  warp:
    description: Base command for warps
